# Site settings
name: Robin C Samuel
title: Robin C Samuel | Engineering Leader | Full-Stack Software Developer/Architect.
description: an engineering lead, full-stack developer, and architect, building secure, scalable applications and driving high-performance engineering teams.
url: https://robinz.in
baseurl: ''
email: hi@robinz.in
cover: https://robinz.in/img/og.png
logo: https://robinz.in/img/emojis/technologist.png
resume: https://www.linkedin.com/in/robincsamuel
social:
  - title: email
    url: mailto:hi@robinz.in
  - title: twitter
    url: https://twitter.com/robincsamuel
  - title: github
    url: https://github.com/robincsamuel
  - title: linkedin
    url: https://www.linkedin.com/in/robincsamuel

# Build settings
markdown: kramdown

include:
  - '_pages'
  - '_posts'

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
